name: hestia
description: A new Flutter project by Tessera ;D

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path:

  sqflite: ^2.0.0+4
  shared_preferences: ^2.0.9
  cupertino_icons: ^1.0.2
  page_transition: ^2.0.2
  sizer: ^2.0.15
  flutter_screenutil: ^5.0.0+2
  font_awesome_flutter: ^9.2.0
  flutter_slidable: ^1.1.0
  path_provider: ^2.0.7
  localstore: ^1.2.1
  flutter_staggered_grid_view: ^0.4.1
  responsive_framework: ^0.1.4
  intl: ^0.17.0
  flutter_masked_text: ^0.8.0
  pie_chart: ^5.1.0
  syncfusion_flutter_charts: ^19.3.56
  http: ^0.13.4
  geolocator: ^3.0.1
  flutter_spinkit: ^3.1.0
  introduction_screen: ^1.0.9
  audioplayers: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
    - audio/

  fonts:
    - family: Poppins-Bold
      fonts:
        - asset: fonts/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: fonts/Poppins-Medium.ttf

    - family: Poppins-Regular
      fonts:
        - asset: fonts/Poppins-Regular.ttf

    - family: Poppins-SemiBold
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf

    - family: Poppins-Thin
      fonts:
        - asset: fonts/Poppins-Thin.ttf

   #Montserrat
    - family: Montserrat-Bold
      fonts:
        - asset: fonts/Montserrat-Bold.ttf

    - family: Montserrat-Medium
      fonts:
        - asset: fonts/Montserrat-Medium.ttf

    - family: Montserrat-Regular
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

    - family: Montserrat-SemiBold
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf

    - family: Montserrat-Thin
      fonts:
        - asset: fonts/Montserrat-Thin.ttf

    - family: Comfortaa-Regular
      fonts:
        - asset: fonts/Comfortaa-Regular.ttf